name: Deploy to VM when push

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MQTT_HOST }}
        username: ${{ secrets.MQTT_USERNAME }}
        key: ${{ secrets.MQTT_KEY }}
        port: 22
        script: |
          cd ~/ipmr-telemetry-worker
          git pull origin master
          cp ~/rest-middleware/utils/config/key.json ./service-account.json || cp ~/industrialpmr-rest-middleware/utils/config/key.json ./service-account.json || true
          npm install --omit=dev
          pm2 startOrReload ecosystem.config.js --update-env
          pm2 save
